services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/project
    command: sleep infinity

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emr
    ports:
      - "5432:5432"

volumes:
  postgres-data:
